// 快捷键描述 - 简体中文
export default {
  'mt.hide': 'MarkText: 隐藏 MarkText',
  'mt.hide-others': 'MarkText: 隐藏其他',
  'file.new-window': '文件: 新建窗口',
  'file.new-tab': '文件: 新建标签页',
  'file.open-file': '文件: 打开文件',
  'file.open-folder': '文件: 打开文件夹',
  'file.save': '文件: 保存',
  'file.save-as': '文件: 另存为...',
  'file.move-file': '文件: 移动...',
  'file.rename-file': '文件: 重命名...',
  'file.quick-open': '文件: 显示快速打开对话框',
  'file.print': '文件: 打印当前标签页',
  'file.preferences': 'MarkText: 偏好设置',
  'file.close-tab': '文件: 关闭当前标签页',
  'file.close-window': '文件: 关闭窗口',
  'file.quit': 'MarkText: 退出',
  'edit.undo': '编辑: 撤销',
  'edit.redo': '编辑: 重做',
  'edit.cut': '编辑: 剪切',
  'edit.copy': '编辑: 复制',
  'edit.paste': '编辑: 粘贴',
  'edit.copy-as-markdown': '编辑: 复制为 Markdown',
  'edit.copy-as-html': '编辑: 复制为 HTML',
  'edit.paste-as-plaintext': '编辑: 粘贴为纯文本',
  'edit.select-all': '编辑: 全选',
  'edit.duplicate': '编辑: 复制行',
  'edit.create-paragraph': '编辑: 创建段落',
  'edit.delete-paragraph': '编辑: 删除段落',
  'edit.find': '编辑: 查找',
  'edit.find-next': '编辑: 查找下一个',
  'edit.find-previous': '编辑: 查找上一个',
  'edit.replace': '编辑: 替换',
  'edit.find-in-folder': '编辑: 在文件夹中查找',
  'edit.screenshot': '编辑: 截图',
  'paragraph.heading-1': '段落: 转换为标题 1',
  'paragraph.heading-2': '段落: 转换为标题 2',
  'paragraph.heading-3': '段落: 转换为标题 3',
  'paragraph.heading-4': '段落: 转换为标题 4',
  'paragraph.heading-5': '段落: 转换为标题 5',
  'paragraph.heading-6': '段落: 转换为标题 6',
  'paragraph.upgrade-heading': '段落: 升级标题',
  'paragraph.degrade-heading': '段落: 降级标题',
  'paragraph.table': '段落: 创建表格',
  'paragraph.code-fence': '段落: 转换为代码块',
  'paragraph.quote-block': '段落: 转换为引用块',
  'paragraph.math-formula': '段落: 转换为数学公式',
  'paragraph.html-block': '段落: 转换为 HTML 块',
  'paragraph.order-list': '段落: 转换为有序列表',
  'paragraph.bullet-list': '段落: 转换为无序列表',
  'paragraph.task-list': '段落: 转换为任务列表',
  'paragraph.loose-list-item': '段落: 转换为宽松列表项',
  'paragraph.paragraph': '段落: 创建新段落',
  'paragraph.horizontal-line': '段落: 插入水平分割线',
  'paragraph.front-matter': '段落: 插入前置元数据',
  'format.strong': '格式: 粗体',
  'format.emphasis': '格式: 斜体',
  'format.underline': '格式: 下划线',
  'format.superscript': '格式: 上标',
  'format.subscript': '格式: 下标',
  'format.highlight': '格式: 高亮',
  'format.inline-code': '格式: 行内代码',
  'format.inline-math': '格式: 行内公式',
  'format.strike': '格式: 删除线',
  'format.hyperlink': '格式: 超链接',
  'format.image': '格式: 插入图片',
  'format.clear-format': '格式: 清除格式',
  'window.minimize': '窗口: 最小化',
  'window.toggle-always-on-top': '窗口: 总在最前',
  'window.zoom-in': '窗口: 放大',
  'window.zoom-out': '窗口: 缩小',
  'window.toggle-full-screen': '窗口: 切换全屏',
  'view.command-palette': '视图: 显示命令面板',
  'view.source-code-mode': '视图: 切换源码模式',
  'view.typewriter-mode': '视图: 切换打字机模式',
  'view.focus-mode': '视图: 专注模式',
  'view.toggle-sidebar': '视图: 切换侧边栏',
  'view.toggle-toc': '视图: 切换目录',
  'view.toggle-tabbar': '视图: 切换标签栏',
  'view.toggle-dev-tools': '视图: 显示开发者工具 (调试)',
  'view.dev-reload': '视图: 重新加载窗口 (调试)',
  'tabs.cycle-forward': '其他: 向前循环标签',
  'tabs.cycle-backward': '其他: 向后循环标签',
  'tabs.switch-to-left': '其他: 切换到左侧标签',
  'tabs.switch-to-right': '其他: 切换到右侧标签',
  'tabs.switch-to-first': '其他: 切换到第 1 个标签',
  'tabs.switch-to-second': '其他: 切换到第 2 个标签',
  'tabs.switch-to-third': '其他: 切换到第 3 个标签',
  'tabs.switch-to-fourth': '其他: 切换到第 4 个标签',
  'tabs.switch-to-fifth': '其他: 切换到第 5 个标签',
  'tabs.switch-to-sixth': '其他: 切换到第 6 个标签',
  'tabs.switch-to-seventh': '其他: 切换到第 7 个标签',
  'tabs.switch-to-eighth': '其他: 切换到第 8 个标签',
  'tabs.switch-to-ninth': '其他: 切换到第 9 个标签',
  'tabs.switch-to-tenth': '其他: 切换到第 10 个标签',
  'view.reload-images': '视图: 强制重新加载图片',
  'file.toggle-auto-save': '文件: 切换自动保存',
  'file.import-file': '文件: 导入...',
  'file.export-file': '文件: 导出...',
  'file.zoom': '窗口: 缩放...',
  'file.check-update': 'MarkText: 检查更新...',
  'paragraph.reset-paragraph': '段落: 转换为段落',
  'window.change-theme': '主题: 切换主题...',
  'view.text-direction': '视图: 设置文字方向',
  'docs.user-guide': 'MarkText: 用户指南',
  'docs.markdown-syntax': 'MarkText: Markdown 语法指南'
}
